# Generated by Django 5.0.4 on 2024-04-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RandomInteger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='значение')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='последнее обновление')),
            ],
        ),
    ]
